dist: trusty
# Work-around for https://github.com/travis-ci/travis-ci/issues/8836.
sudo: required
language: node_js
node_js:
  - 8
  - 10

env:
  - TEST_REPORT=lcovonly TEST_COMMAND=test:coverage

after_success:
  - cat coverage/lcov.info | coveralls
